version: '3.7'
services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=default
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 12g
        reservations:
          cpus: '0.25'
          memory: 4g
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: clickhouse
    ports:
      - "8123:8123"
    volumes:
      - ./.volumes/clickhouse:/var/lib/clickhouse

  client:
    image: yandex/clickhouse-client
    container_name: clickhouse-client
    restart: always
    entrypoint:
      - /bin/sleep
    command:
      - infinity

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: clickhouse-tabix-web-client
    restart: always
    ports:
      - "8081:80"
    environment:
      - CH_HOST=clickhouse:8123

  prometheus:
    image: prom/prometheus:latest
    sysctls:
      - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv6.conf.all.disable_ipv6=0
    container_name: prometheus
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    volumes:
      - ./.volumes/prometheus/:/prometheus
      - ./docker/prometheus/:/etc/prometheus/
    expose:
      - 9090
    ports:
      - "0.0.0.0:9090:9090/tcp"

  cadvisor:
    image: 'zcube/cadvisor:latest'
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8083:8080'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64m
    volumes:
      - ./.volumes/alertmanager/:/alertmanager
      - ./docker/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    expose:
      - 9093
    ports:
      - "0.0.0.0:9093:9093/tcp"

  alertmanager-discord:
    image: lidofinance/alertmanager-discord:2.7.0
    platform: linux/x86_64
    container_name: alertmanager-discord
    restart: unless-stopped
    environment:
      - WORKING_MODE=alternative
      - PORT=9094
    expose:
      - 9094
    ports:
      - "0.0.0.0:9094:9094/tcp"
    volumes:
      - ./docker/alertmanager-discord/alertmanager-discord.yml:/etc/alertmanager-discord.yml

  grafana:
    image: grafana/grafana:9.5.7
    sysctls:
      - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv6.conf.all.disable_ipv6=0
    container_name: grafana
    hostname: grafana.local
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 192m
    links:
      - prometheus:prometheus
    volumes:
      - ./.volumes/grafana/:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=locahost
      - GF_SMTP_ENABLED=false
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
      - CLICKHOUSE_DB_HOST=http://clickhouse
      - CLICKHOUSE_DB_PORT=8123
      - CLICKHOUSE_DB_USER=default
      - CLICKHOUSE_DB_PASSWORD=
      - CLICKHOUSE_DB_NAME=default
    ports:
      - "8082:3000"

  app:
    build: ./
    container_name: ethereum-validators-monitoring
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 5g
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - WORKING_MODE=${WORKING_MODE:-finalized}
      - NODE_ENV=${NODE_ENV:-development}
      - DRY_RUN=${DRY_RUN:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - DB_HOST=http://clickhouse
      - DB_PORT=8123
      - DB_USER=default
      - DB_PASSWORD=
      - DB_NAME=default
      - DB_MAX_RETRIES=${DB_MAX_RETRIES:-10}
      - DB_MIN_BACKOFF_SEC=${DB_MIN_BACKOFF_SEC:-1}
      - DB_MAX_BACKOFF_SEC=${DB_MAX_BACKOFF_SEC:-120}
      - START_EPOCH=${START_EPOCH:-155000}
      - ETH_NETWORK=${ETH_NETWORK}
      - VALIDATOR_REGISTRY_SOURCE=${VALIDATOR_REGISTRY_SOURCE:-lido}
      - VALIDATOR_REGISTRY_FILE_SOURCE_PATH=${VALIDATOR_REGISTRY_FILE_SOURCE_PATH:-./docker/validators/custom_mainnet.yaml}
      - VALIDATOR_REGISTRY_LIDO_SOURCE_SQLITE_CACHE_PATH=${VALIDATOR_REGISTRY_LIDO_SOURCE_SQLITE_CACHE_PATH:-./docker/validators/lido_mainnet.db}
      - VALIDATOR_USE_STUCK_KEYS_FILE=${VALIDATOR_USE_STUCK_KEYS_FILE:-false}
      - VALIDATOR_STUCK_KEYS_FILE_PATH=${VALIDATOR_STUCK_KEYS_FILE_PATH:-./docker/validators/stuck_keys.yaml}
      - VALIDATOR_REGISTRY_KEYSAPI_SOURCE_URLS=${VALIDATOR_REGISTRY_KEYSAPI_SOURCE_URLS}
      - VALIDATOR_REGISTRY_KEYSAPI_SOURCE_RETRY_DELAY_MS=${VALIDATOR_REGISTRY_KEYSAPI_SOURCE_RETRY_DELAY_MS:-500}
      - VALIDATOR_REGISTRY_KEYSAPI_SOURCE_RESPONSE_TIMEOUT=${VALIDATOR_REGISTRY_KEYSAPI_SOURCE_RESPONSE_TIMEOUT:-30000}
      - VALIDATOR_REGISTRY_KEYSAPI_SOURCE_MAX_RETRIES=${VALIDATOR_REGISTRY_KEYSAPI_SOURCE_MAX_RETRIES:-2}
      - EL_RPC_URLS=${EL_RPC_URLS}
      - CL_API_URLS=${CL_API_URLS}
      - CL_API_RETRY_DELAY_MS=${CL_API_RETRY_DELAY_MS:-500}
      - CL_API_GET_RESPONSE_TIMEOUT=${CL_API_GET_RESPONSE_TIMEOUT:-15000}
      - CL_API_MAX_RETRIES=${CL_API_MAX_RETRIES:-1}
      - CL_API_GET_BLOCK_INFO_MAX_RETRIES=${CL_API_GET_BLOCK_INFO_MAX_RETRIES:-1}
      - FETCH_INTERVAL_SLOTS=${FETCH_INTERVAL_SLOTS:-32}
      - CHAIN_SLOT_TIME_SECONDS=${CHAIN_SLOT_TIME_SECONDS:-12}
      - BAD_ATTESTATION_EPOCHS=${BAD_ATTESTATION_EPOCHS:-3}
      - CRITICAL_ALERTS_ALERTMANAGER_URL=${CRITICAL_ALERTS_ALERTMANAGER_URL}
      - CRITICAL_ALERTS_MIN_VAL_COUNT=${CRITICAL_ALERTS_MIN_VAL_COUNT:-100}
      - CRITICAL_ALERTS_ALERTMANAGER_LABELS=${CRITICAL_ALERTS_ALERTMANAGER_LABELS:-{}}
    expose:
      - "${HTTP_PORT:-8080}"
    ports:
      - "${EXTERNAL_HTTP_PORT:-${HTTP_PORT:-8080}}:${HTTP_PORT:-8080}"
    volumes:
      - ./docker/validators/:/app/docker/validators
    depends_on:
      - clickhouse
      - prometheus

networks:
  default:
    name: dev_validators_monitoring
    driver_opts:
      com.docker.network.bridge.name: dev-val-mon
